Basiacarvalho/feature/movie list body
piotrlewoniec/filmoteka pull request #4
Opened 2023-06-09 14:08 UTC by basiacarvalho

Przesyłam całą sekcję movie-list

2023-06-09 16:43 UTC, piotrlewoniec commented on src/sass/partials/_movie-list.scss
Please consider using @use '../utils/variables' as var; instead only  @use '../utils/variables' ; for future code re-use.
After file name changed you can make one change and also two of developers already using it so for keeping code standard. (najlepsze jest, że nie wiem czy pro o takie coś by zwrócił uwagę :D , wieć trudno How bad is my english ? XD )

2023-06-09 16:46 UTC, piotrlewoniec commented on src/sass/utils/_mediaquery.scss
line 14 you added + ?

2023-06-09 16:53 UTC, piotrlewoniec requested changes
Please take a look for given comments

2023-06-10 10:20 UTC, basiacarvalho commented on src/sass/partials/_movie-list.scss
Ok, done :)

2023-06-10 10:38 UTC, piotrlewoniec approved these changes
OK

2023-06-10 10:46 UTC, merged