feature/my library header html and css
piotrlewoniec/filmoteka pull request #5
Opened 2023-06-09 14:24 UTC by tojaarek

dodany sprint icons wraz z grafikami

2023-06-09 16:06 UTC, piotrlewoniec commented on src/css/main.min.css
Please, do not use external sass extensions in VSC.
Parcel has it own. Switch this off and delete folder css

2023-06-09 16:06 UTC, piotrlewoniec commented on src/css/main.min.css.map
Parcel has it own. Switch this off and delete folder css

2023-06-09 16:12 UTC, piotrlewoniec commented on src/partials/my-library.html
1. Please delete this line:
<link rel="stylesheet" href='../css/main.min.css' />  - it is done by parcel
2. Also please put in comment:
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.1.0/modern-normalize.min.css"
    integrity="sha512-wpPYUAdjBVSE4KJnH1VR1HeZfpl1ub8YT/NKx4PuQ5NmX2tKuGu6U/JRp5y+Y8XG2tV+wKQpNHVUX03MfMFn9Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
3. I suggest to build this file like index.html using includes for header main section and footer (footer is the same for both files, so in here we can also make include of footer file.
4. Possibly there will be problems with scripts integration - but I propose to test it  :)

2023-06-09 16:14 UTC, piotrlewoniec commented on src/sass/main.scss
Please move this line @use './partials/header'; after line 8: @use './utils/reset';

2023-06-09 16:20 UTC, piotrlewoniec commented on src/sass/partials/_header.scss
please consider using mixin for that:
@media (min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)
you can find it in mediaquery also (I guess they should work :D )

2023-06-09 16:27 UTC, piotrlewoniec commented
Please consider using awilczynski or arekwilczynski for branch naming f.e. arekwilczynski/feature/mylibrary (without white spaces)

2023-06-09 16:54 UTC, piotrlewoniec requested changes
Please take a look for given comments

2023-06-10 07:18 UTC, tojaarek reviewed
Changes made

2023-06-10 07:25 UTC, merged